# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20160622_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder',
        ),
    ]
