# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20160622_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=250),
        ),
    ]
